name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"   # Runs every day at 8 AM

permissions:
  contents: write
  
jobs:
  build:
      name: generate-github-profile-3d-contrib
      runs-on: ubuntu-latest
      steps:
        - uses: athul/waka-readme@master 
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        - uses: actions/checkout@v4
        - uses: yoshi389111/github-profile-3d-contrib@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
            USERNAME: ${{ github.repository_owner }}
        - name: Commit & Push
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add -A .
            if git commit -m "generated"; then
              git push
            fi
